### ISSUE TITLE
Asset references to materials getting corrupted

### ISSUE THREAD

**Issue by Jumbli** [StereoKit/StereoKit#535]
## Description
I've always experienced problems with crashes related to copying models and materials on various versions of StereoKit. So, I've created a sample VSCode project to force the issue (tested on 0.3.7-preview5 & 0.3.7-preview6). In this code I load 100 models, each with its own material. Wait a few minutes and then it crashes when trying to set the colour on a material. If you click the button again to load another 100 models it will crash more quickly.

This happens in my project with just a handful of models, I'm just using brute force to try and reproduce it. It feels like it's something to do with garbage collection clearing references that are still in use.

When the crash occurs it will be on a random model. The material with not be null, but if you try and add a watch on the material it will fail.

## Platform / Environment
Testing this on Windows Oculus Rift

## VSCode sample project
```
using StereoKit;

Pose pose = new Pose(V.XYZ(0,0,-1),Quat.FromAngles(0,180,0));

List<TestModel> models = new List<TestModel>();
string[] modelFilenames = {"_1cone.obj", "_1cube.obj", "_1cylinder.obj"}; // any models will do
int modelCount = modelFilenames.Count();

Random r = new Random();

float  timeModelsLoaded = -1;

SK.Initialize();
SK.Run(()=>{
    UI.WindowBegin("Material reference testings",ref pose);
    
    if (UI.Button("1. Add 100 models"))
    {
        for (int j=0;j<100;j++)
            AddModel(modelFilenames[(j % modelCount)]);

        if (timeModelsLoaded == -1)
            timeModelsLoaded = Time.Totalf;
    }
    
    if (timeModelsLoaded > 0)
        UI.Label("Wait a few minutes for a crash " + (int)(Time.Totalf - timeModelsLoaded));        
     
    UI.WindowEnd();

    int i=0;
    foreach (TestModel m in models) {
            ChangeColour(m.model);
            m.model.Draw(Matrix.TS(V.XYZ(SKMath.Lerp(-5f,5f,(float)i / models.Count),0,-2),-.02f));
        i++;
    }
});

void AddModel(string filename, int inx = -1)
{
        Model m = Model.FromFile(filename);
        m = m.Copy();
        
        for (int i = 0; i < m.Nodes.Count; i++)
        {                                    
            if (m.Nodes[i].Material != null)
                m.Nodes[i].Material = m.Nodes[i].Material.Copy();
        }
        if (inx == -1)
            models.Add(new TestModel(m));
        else
            models.ElementAt(inx).model = m;

}


void ChangeColour(Model model)
{

    for (int i = 0; i < model.Nodes.Count; i++)
    {
        if (model.Nodes[i].Material != null)
            model.Nodes[i].Material.SetColor("color", Color.White * r.NextSingle());
    }
 
}

class TestModel
{
    public Model model;
    public TestModel(Model newModel)
    {
        model = newModel;
    }
}
```
## Logs or exception details
```
[SK Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at StereoKit.NativeAPI.material_set_color(IntPtr, System.String, StereoKit.Color)
--------------------------------
   at Program+<>c__DisplayClass0_0.<<Main>$>g__ChangeColour|2(StereoKit.Model)
   at Program+<>c__DisplayClass0_0.<<Main>$>b__0()
   at StereoKit.SK._Step()
   at StereoKit.NativeAPI.sk_run(System.Action, System.Action)
   at StereoKit.NativeAPI.sk_run(System.Action, System.Action)
   at Program.<Main>$(System.String[])
The program '[21120] skTest.dll' has exited with code -1073741819 (0xc0000005).
```
## Similar errors
I also see these two crashes in my project, which may be a variation of where the problem is first encountered in the code:
```
[SK error] Released too many references to asset!
Crashes out with: MyProjectName.exe (process 14360) exited with code -1073740791.
```
```
[SK error] Destroying asset '(null)' that still has references!
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at StereoKit.NativeAPI.material_get_param_count(IntPtr)
   at StereoKit.NativeAPI.material_get_param_count(IntPtr)
   at StereoKit.Material.get_ParamCount()
   at Node.Draw()
   at Main.Draw()
   at StereoKitApp.App.Step()
   at StereoKit.SK._Step()
   at StereoKit.NativeAPI.sk_step(System.Action)
   at StereoKit.NativeAPI.sk_step(System.Action)
   at SKLoader.Main(System.String[])
```

**Comment by maluoi** [comment]
Thanks a bunch for the details and code! I just checked, and I can indeed reliably re-create this crash with your example here, so this is perfect for me!

Today and tomorrow are holidays for me, but I'll dig into this right after, I have a few thoughts about what this could be already!

**Comment by maluoi** [comment]
Sample code was super helpful, I'm pretty sure I was able to nail this one down! I'll be doing some on-device testing tomorrow, but this seemed to completely eliminate the issue on PC. Should have a preview build out this week.

**Comment by Jumbli** [comment]
Great, thanks. I will give it a test once released.

**Comment by maluoi** [comment]
v0.3.7-preview.7 is now available on NuGet, please feel free to re-open if the problem persists :)
