### ISSUE TITLE
dotnet run / watch on MacOS cannot load StereoKitC

### ISSUE THREAD

**Issue by mrstruijk** [StereoKit/StereoKit#775]
## Description
When do either `dotnet run` or `dotnet watch`, the logs state that StereoKitC cannot be found, even though it's installed, and building to device works as well. Is this something Mac specific, or am I doing something wrong? I get the issue when doing the exact steps in the [Getting Started VS Code documentation](https://stereokit.net/Pages/Guides/Getting-Started-VS-Code.html)

## Platform / Environment
I'm working on M1 macOS 14.1, I'm using latest VS Code 1.84.1. I've installed dotnet 7.0.483, the android workload, openJDK 17, Android API level 33 via Android Studio, Xamarin via VS.
Stereokit was installed (latest), as was the Templates (latest)

## Logs or exception details
➜  ProjectName dotnet run
[SK error] Failed to load StereoKitC!
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'StereoKitC' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/StereoKitC.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/StereoKitC.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/StereoKitC.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/StereoKitC.dylib' (no such file)
dlopen(/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/StereoKitC.dylib, 0x0001): tried: '/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/StereoKitC.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/StereoKitC.dylib' (no such file), '/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/StereoKitC.dylib' (no such file)
dlopen(StereoKitC.dylib, 0x0001): tried: 'StereoKitC.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSStereoKitC.dylib' (no such file), '/usr/lib/StereoKitC.dylib' (no such file, not in dyld cache), 'StereoKitC.dylib' (no such file), '/usr/local/lib/StereoKitC.dylib' (no such file), '/usr/lib/StereoKitC.dylib' (no such file, not in dyld cache)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/libStereoKitC.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/libStereoKitC.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/libStereoKitC.dylib' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/libStereoKitC.dylib' (no such file)
dlopen(/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/libStereoKitC.dylib, 0x0001): tried: '/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/libStereoKitC.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/libStereoKitC.dylib' (no such file), '/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/libStereoKitC.dylib' (no such file)
dlopen(libStereoKitC.dylib, 0x0001): tried: 'libStereoKitC.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibStereoKitC.dylib' (no such file), '/usr/lib/libStereoKitC.dylib' (no such file, not in dyld cache), 'libStereoKitC.dylib' (no such file), '/usr/local/lib/libStereoKitC.dylib' (no such file), '/usr/lib/libStereoKitC.dylib' (no such file, not in dyld cache)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/StereoKitC, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/StereoKitC' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/StereoKitC' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/StereoKitC' (no such file)
dlopen(/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/StereoKitC, 0x0001): tried: '/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/StereoKitC' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/StereoKitC' (no such file), '/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/StereoKitC' (no such file)
dlopen(StereoKitC, 0x0001): tried: 'StereoKitC' (no such file), '/System/Volumes/Preboot/Cryptexes/OSStereoKitC' (no such file), '/usr/lib/StereoKitC' (no such file, not in dyld cache), 'StereoKitC' (no such file), '/usr/local/lib/StereoKitC' (no such file), '/usr/lib/StereoKitC' (no such file, not in dyld cache)
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/libStereoKitC, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/libStereoKitC' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/libStereoKitC' (no such file), '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.13/libStereoKitC' (no such file)
dlopen(/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/libStereoKitC, 0x0001): tried: '/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/libStereoKitC' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/libStereoKitC' (no such file), '/Users/mrstruijk/Current StereoKit Projects/ProjectName/bin/Debug/net7.0/libStereoKitC' (no such file)
dlopen(libStereoKitC, 0x0001): tried: 'libStereoKitC' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibStereoKitC' (no such file), '/usr/lib/libStereoKitC' (no such file, not in dyld cache), 'libStereoKitC' (no such file), '/usr/local/lib/libStereoKitC' (no such file), '/usr/lib/libStereoKitC' (no such file, not in dyld cache)

   at StereoKit.NativeAPI.sk_step(Action app_update)
   at StereoKit.SK.Step(Action onStep) in /_/StereoKit/SK.cs:line 198
   at StereoKit.SK.Run(Action onStep, Action onShutdown) in /_/StereoKit/SK.cs:line 227
   at Program.<Main>$(String[] args) in /Users/mrstruijk/Current StereoKit Projects/ProjectName/Program.cs:line 4

**Comment by mrstruijk** [comment]
Ajjj! That's unfortunate. Not a worry though. Thanks for the info :)
